using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Atomic.CodeGen.Core.Models;
using Atomic.CodeGen.Rename.Models;
using Atomic.CodeGen.Roslyn;
using Atomic.CodeGen.Utils;
using Microsoft.CodeAnalysis;

namespace Atomic.CodeGen.Rename.UsageFinders;

public sealed class SemanticDomainUsageFinder
{
	private readonly string _solutionPath;

	private readonly AnalyzerMode _analyzerMode;

	private readonly IEnumerable<string>? _includedProjects;

	private static readonly Regex SourceFilePathRegex = new Regex("^\\s*\\*\\s*Source file path:\\s*(.+?)\\s*$", RegexOptions.Multiline | RegexOptions.Compiled);

	public SemanticDomainUsageFinder(string solutionPath, AnalyzerMode analyzerMode = AnalyzerMode.Auto, IEnumerable<string>? includedProjects = null)
	{
		_solutionPath = solutionPath;
		_analyzerMode = analyzerMode;
		_includedProjects = includedProjects;
	}

	public async Task<List<UsageMatch>> FindUsagesAsync(RenameContext context)
	{
		List<UsageMatch> results = new List<UsageMatch>();
		string entityName = context.OldName;
		string newEntityName = context.NewName;
		string domainSourceFile = context.SourceFilePath;
		using SemanticWorkspace workspace = new SemanticWorkspace(_solutionPath, _analyzerMode, _includedProjects);
		if (!(await workspace.LoadAsync()))
		{
			Logger.LogWarning("Failed to load solution for semantic analysis.");
			return results;
		}
		HashSet<string> generatedFiles = new HashSet<string>(StringComparer.OrdinalIgnoreCase) { Path.GetFullPath(domainSourceFile) };
		foreach (Project project in workspace.Projects)
		{
			foreach (Document doc in project.Documents)
			{
				if (doc.FilePath != null)
				{
					string content = await File.ReadAllTextAsync(doc.FilePath);
					if (IsGeneratedByDomain(doc.FilePath, content, domainSourceFile))
					{
						generatedFiles.Add(Path.GetFullPath(doc.FilePath));
					}
				}
			}
		}
		Logger.LogVerbose($"Found {generatedFiles.Count} files generated by this domain");
		List<Atomic.CodeGen.Roslyn.SemanticUsage> semanticUsages = await workspace.FindUsagesOfTypesFromFilesAsync(generatedFiles);
		Logger.LogVerbose($"Semantic analysis found {semanticUsages.Count} usages");
		foreach (Atomic.CodeGen.Roslyn.SemanticUsage usage in semanticUsages)
		{
			string newSymbolName = usage.SymbolName.Replace(entityName, newEntityName);
			if (!(newSymbolName == usage.SymbolName))
			{
				string lineContext = await GetLineContextAsync(usage.FilePath, usage.Line);
				results.Add(new UsageMatch
				{
					FilePath = usage.FilePath,
					Line = usage.Line,
					Column = usage.Column,
					Length = usage.Length,
					MatchedText = usage.SymbolName,
					ReplacementText = newSymbolName,
					LineContext = lineContext,
					Category = GetCategory(usage.SymbolName, entityName),
					IsAmbiguous = false
				});
			}
		}
		await FindEntityNamePropertyAsync(domainSourceFile, entityName, newEntityName, results);
		foreach (string generatedFile in generatedFiles)
		{
			if (!generatedFile.Equals(Path.GetFullPath(domainSourceFile), StringComparison.OrdinalIgnoreCase))
			{
				string fileName = Path.GetFileName(generatedFile);
				if (fileName.Contains(entityName))
				{
					string renamedFileName = fileName.Replace(entityName, newEntityName);
					string renamedFilePath = Path.Combine(Path.GetDirectoryName(generatedFile) ?? "", renamedFileName);
					context.FileRenames.Add((generatedFile, renamedFilePath));
				}
			}
		}
		return results;
	}

	private bool IsGeneratedByDomain(string filePath, string content, string domainSourceFile)
	{
		string normalizedFilePath = Path.GetFullPath(filePath).Replace('/', '\\');
		string normalizedDomainPath = Path.GetFullPath(domainSourceFile).Replace('/', '\\');
		if (normalizedFilePath.Equals(normalizedDomainPath, StringComparison.OrdinalIgnoreCase))
		{
			return false;
		}
		string input = string.Join("\n", content.Split('\n').Take(10));
		Match match = SourceFilePathRegex.Match(input);
		if (!match.Success)
		{
			return false;
		}
		string referencedSourcePath = match.Groups[1].Value.Trim().Replace('/', '\\');
		if (!Path.IsPathRooted(referencedSourcePath))
		{
			string fileName = Path.GetFileName(normalizedDomainPath);
			if (referencedSourcePath.EndsWith(fileName, StringComparison.OrdinalIgnoreCase))
			{
				return true;
			}
		}
		else
		{
			referencedSourcePath = Path.GetFullPath(referencedSourcePath).Replace('/', '\\');
			if (referencedSourcePath.Equals(normalizedDomainPath, StringComparison.OrdinalIgnoreCase))
			{
				return true;
			}
		}
		return false;
	}

	private async Task<string> GetLineContextAsync(string filePath, int lineNumber)
	{
		try
		{
			string[] fileLines = await File.ReadAllLinesAsync(filePath);
			if (lineNumber > 0 && lineNumber <= fileLines.Length)
			{
				return fileLines[lineNumber - 1].TrimEnd('\r');
			}
		}
		catch
		{
		}
		return "";
	}

	private async Task FindEntityNamePropertyAsync(string filePath, string entityName, string newEntityName, List<UsageMatch> results)
	{
		if (!File.Exists(filePath))
		{
			return;
		}
		string[] sourceLines = (await File.ReadAllTextAsync(filePath)).Split('\n');
		Regex regex = new Regex("EntityName\\s*=>\\s*\"" + Regex.Escape(entityName) + "\"");
		int lineNumber = 0;
		foreach (string line in sourceLines)
		{
			lineNumber++;
			foreach (Match regexMatch in regex.Matches(line))
			{
				results.Add(new UsageMatch
				{
					FilePath = filePath,
					Line = lineNumber,
					Column = regexMatch.Index + 1,
					Length = regexMatch.Length,
					MatchedText = regexMatch.Value,
					ReplacementText = "EntityName => \"" + newEntityName + "\"",
					LineContext = line.TrimEnd('\r'),
					Category = "EntityNameProperty",
					IsAmbiguous = false
				});
			}
		}
	}

	private string GetCategory(string symbolName, string entityName)
	{
		if (symbolName.StartsWith("I") && symbolName.Length > 1 && char.IsUpper(symbolName[1]))
		{
			return "Interface";
		}
		if (symbolName.StartsWith("Scene"))
		{
			if (!symbolName.Contains("World"))
			{
				if (!symbolName.Contains("Proxy"))
				{
					return "SceneEntity";
				}
				return "SceneProxy";
			}
			return "SceneWorld";
		}
		if (symbolName.EndsWith("Behaviours"))
		{
			return "Behaviours";
		}
		if (symbolName.EndsWith("Factory"))
		{
			return "Factory";
		}
		if (symbolName.EndsWith("Pool"))
		{
			return "Pool";
		}
		if (symbolName.EndsWith("Installer"))
		{
			return "Installer";
		}
		if (symbolName.EndsWith("Baker"))
		{
			return "Baker";
		}
		if (symbolName.EndsWith("View"))
		{
			return "View";
		}
		if (symbolName.EndsWith("Aspect"))
		{
			return "Aspect";
		}
		if (symbolName == entityName)
		{
			return "EntityType";
		}
		return "Type";
	}

	public static string? FindSolutionFile(string projectRoot)
	{
		return Directory.GetFiles(projectRoot, "*.sln", SearchOption.TopDirectoryOnly)
			.Concat(Directory.GetFiles(projectRoot, "*.slnx", SearchOption.TopDirectoryOnly))
			.FirstOrDefault();
	}
}
